adx_displayorder: 4
adx_enablerating: false
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_isroot: true
adx_name: Training content
adx_pagetemplateid: fb9076b2-b512-ed11-b83d-000d3a54e5f5
adx_parentpageid: 87887fb8-b512-ed11-b83d-000d3a54e5f5
adx_partialurl: training-content
adx_publishingstateid: 109176b2-b512-ed11-b83d-000d3a54e5f5
adx_sharedpageconfiguration: true
adx_webpageid: 87d5f868-4e13-ed11-b83d-000d3a54e5f5
